# Generated by Django 5.0 on 2023-12-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('extension', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.CharField(max_length=50)),
                ('faculty_persian', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_id', models.IntegerField()),
                ('content', models.TextField()),
                ('content_persian', models.TextField()),
                ('privacy', models.TextField()),
                ('privacy_persian', models.TextField()),
                ('services', models.TextField()),
                ('services_persian', models.TextField()),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=255)),
                ('news_summary', models.TextField()),
                ('news_details', models.TextField()),
                ('news_ref', models.CharField(max_length=255)),
                ('news_title_persian', models.CharField(max_length=255)),
                ('news_summary_persian', models.TextField()),
                ('news_details_persian', models.TextField()),
                ('news_ref_persian', models.CharField(max_length=255)),
                ('news_date', models.DateTimeField()),
                ('fileext', models.CharField(max_length=3)),
                ('faculties_id', models.IntegerField()),
            ],
        ),
    ]
