# Generated by Django 5.0 on 2023-12-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
