# Generated by Django 5.0 on 2023-12-28 09:18

from django.db import migrations


def create_genders(apps, schema_editor):
    gender = apps.get_model('usermanagement', 'Gender')
    gender.objects.create(gender=0)
    gender.objects.create(gender=1)


roles = ['student', 'professor', 'employee']


def create_roles(apps, schema_editor):
    role = apps.get_model('usermanagement', 'Role')
    for r in roles:
        role.objects.create(role_name=r)


class Migration(migrations.Migration):
    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_genders),
        migrations.RunPython(create_roles),
    ]
